### PR TITLE
update to async-http-client 1.8.1

### PR DESCRIPTION
**Pull request by imod**
update async-http-client to newest version: 1.8.1

### CODE REVIEW

**Comment by imod** [comment]
@stephenc what do you think about updating this?

**Comment by stephenc** [comment]
Would need to cross check that consumers are unaffected by some of the
breaking api changes

On Friday, 31 January 2014, Dominik Bartholdi notifications@github.com
wrote:

> @stephenc https://github.com/stephenc what do you think about updating
> this?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/jenkinsci/async-http-client-plugin/pull/2#issuecomment-33830178
> .

## 

Sent from my phone

**Comment by imod** [comment]
There seem to be four depending plugins:  http://imod.github.io/jenkins-stats/jenkinsgraph.html?filter=http select the `Async Http Client Plugin` and all the depending plugins will appear.
- Maven Deployment Linker, this one is fine, I tested it
- Cloudbees Free Enterprise Plugins
- Jenkins Enterprise by Cloudbees 
- CRX Content Package Deployer Plugin

**Comment by stephenc** [comment]
Also some close source ones we have

On Saturday, 1 February 2014, Dominik Bartholdi notifications@github.com
wrote:

> There seem to be four depending plugins:
> http://imod.github.io/jenkins-stats/jenkinsgraph.html?filter=http select
> the Async Http Client Plugin and all the depending plugins will appear.
> - Maven Deployment Linker, this one is fine, I tested it
> - Cloudbees Free Enterprise Plugins
> - Jenkins Enterprise by Cloudbees
> - CRX Content Package Deployer Plugin
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/jenkinsci/async-http-client-plugin/pull/2#issuecomment-33866185
> .

## 

Sent from my phone

**Comment by varyvol** [comment]
Closing since a new version is already in place.

**Pull request closed without merging**
