### PR TITLE
Configured FindBugs xml output

### PR DESCRIPTION
**Pull request by rsandell**
So Jenkins can pick it up

@reviewbybees

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by varmenise** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by rsandell** [comment]
@reviewbybees done

**Comment by ghost** [comment]
This pull request has completed our internal processes and we now respectfully request the maintainers of this repository to consider our proposal contained within this pull request for merging.

**Pull request merged**
