### PR TITLE
[JENKINS-66887] Enable jdk11 build on CI for linux and windows

### PR DESCRIPTION
**Pull request by aHenryJard**
`recommendedConfigurations` is not building jdk11 anymore. Adding it explicitly.

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by Vlatombe — COMMENTED** [review]
Weird build error. I would suggest to bump parent pom and retry.

**Comment by batmat** [comment]
Superseded by https://github.com/jenkinsci/async-http-client-plugin/pull/33

**Comment by batmat** [comment]
Local build after bumping the parent pom reveals an access-modifier error (there was a bug long ago with the old parent pom...)

```
[INFO] --- access-modifier-checker:1.25:enforce (default-enforce) @ async-http-client ---
[ERROR] jenkins/plugins/asynchttpclient/AHCUtils:60 hudson/ProxyConfiguration.noProxyHost must not be used
[ERROR] jenkins/plugins/asynchttpclient/AHCUtils:61 hudson/ProxyConfiguration.noProxyHost must not be used
```

I'm lacking the time to fix this now.

**Comment by batmat** [comment]
See #33

**Pull request closed without merging**
